actors:
  kokorokagami:
    image_url: /images/actors/kokorokagami.png
    name: kokorokagami
    url: https://twitter.com/TakenoriKusaka
  touden:
    image_url: /images/actors/touden.png
    name: touden
    url: https://twitter.com/touden256?lang=en
author: kokorokagami
description: Recalogは一週間にあったニュースや記事からkokorokagamiとtoudenがピックアップして話す番組です\n https://listen.style/p/recalog?bqOBxHVT
description_long: Recalogは一週間にあったニュースや記事に対しkokorokagamiとtoudenが色々コメントしたり雑談する番組です。Tech系をメインに政治、経済、社会など幅広くとりあげます。中の人はエンジニアですが専門外のことを基本話しているので参考程度にお聞きください。\n https://listen.style/p/recalog?bqOBxHVT
email: rercalog@gmail.com
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
hashtag: Recalog
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
# timezone: Asia/Kyoto
title: Recalog
url: https://takenori-kusaka.github.io/
