actors:
  kokorokagami:
    image_url: /images/actors/kokorokagami.png
    name: kokorokagami
    url: https://twitter.com/TakenoriKusaka
  touden:
    image_url: /images/actors/touden.png
    name: touden
    url: https://twitter.com/touden256?lang=en
author: kokorokagami
description: RecalogはkokorokagamiとtoudenによるVoice Logです
description_long: Recalogはこれまでの振り返りを週単位で行うVoice Logです。techおよび時事ネタが主。
email: Rercalog@gmail.com
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
hashtag: Recalog
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Kyoto
title: Recalog
url: https://takenori-kusaka.github.io/
