actors:
  kokorokagami:
    image_url: /images/actors/kokorokagami.png
    name: kokorokagami
    url: https://twitter.com/TakenoriKusaka
  touden:
    image_url: /images/actors/touden.png
    name: touden
    url: https://twitter.com/touden256?lang=en
author: kokorokagami
description: Rercalog is a Voice Log by kokorokagami with touden.
description_long: Rercalog is a Voice Log that "recall" by week. Theme is tech and current topics.
email: rercalog@gmail.com
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
hashtag: Rercalog
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Kyoto
title: Rercalog
url: https://takenori-kusaka.github.io/
