actors:
  kokorokagami:
    image_url: /images/actors/kokorokagami.png
    name: kokorokagami
    url: http://sns.example.com/kokorokagami
  touden:
    image_url: /images/actors/touden.png
    name: touden
    url: http://sns.example.com/touden
author: kokorokagami
description: Example description
description_long: Example long description
email: CreateThisWhen2DecideTheTitle@example.com
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
hashtag: CreateThisWhen2DecideTheTitle
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Kyoto
title: Awesome title
url: http://CreateThisWhen2DecideTheTitle.com
