# This is a basic workflow to help you get started with Actions

name: whisper

# Controls when the workflow will run
on:
  pull_request:
    types:
      - opened
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  whisper:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Convert to text from m4a
      - name: Run a one-line script
        run: ./src/whisper.ps1

      # Git push
      - name: Git push
        run: |
          git add .
          git commit -m "add text" -a
          git pull
          git push origin master
